# Generated by Django 6.0.6 on 2026-06-28 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneylog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provisioning', models.BooleanField(default=False, help_text='Abilita il provisioning automatico', verbose_name='Provisioning')),
                ('month', models.IntegerField(default=1, help_text='Mese di riferimento (1-12)', verbose_name='Mese')),
                ('payday', models.IntegerField(default=1, help_text='Giorno del mese in cui viene accreditato lo stipendio', verbose_name='Giorno di paga')),
                ('months', models.IntegerField(default=12, help_text='Numero di mesi da considerare nei calcoli', verbose_name='Mesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impostazione',
                'verbose_name_plural': 'Impostazioni',
                'db_table': 'settings',
            },
        ),
    ]
