# Generated by Django 6.0.6 on 2026-06-28 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneylog', '0002_add_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data di competenza della provvigione', verbose_name='Data')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importo della provvigione (positivo = entrata, negativo = uscita)', max_digits=12, verbose_name='Importo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provvigione',
                'verbose_name_plural': 'Provvigioni',
                'db_table': 'provisions',
                'ordering': ['-date'],
            },
        ),
    ]
