# Generated by Django 6.0.7 on 2026-07-25 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneylog', '0003_add_provision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='month',
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('closed', 'Chiuso'), ('open', 'Aperto'), ('main', 'Principale')], default='open', max_length=50, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Attivo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='moneylog.account', verbose_name='Conto'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importo'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='moneylog.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
