# Generated by Django 6.0.7 on 2026-08-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneylog', '0004_remove_setting_month_alter_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='related_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_pair', to='moneylog.movement', verbose_name='Movimento correlato'),
        ),
    ]
